name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache Buildozer dependencies
      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install Buildozer and system dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install --user --upgrade buildozer
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            zip \
            unzip \
            build-essential \
            git \
            ffmpeg \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            autoconf \
            libffi-dev \
            libssl-dev \
            automake \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libreadline-dev \
            libncursesw5-dev \
            uuid-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
            libgstreamer1.0 \
          export PATH=$PATH:~/.local/bin/
          sudo apt-get install libtool
          pip install -U cython
          sudo apt-get update
          sudo apt-get install libtool
          sudo apt-get install build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi6
          sudo apt-get install libffi-dev
          sudo apt install build-essential autoconf libtool
          

      # Build with Buildozer
      - name: Build Android APK
        id: buildozer
        run: |
          buildozer android debug

      # Upload build artifacts
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: bin/*.apk
