name: Build Kivy App

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:
    branches:
      - main  # Change to your default branch if different

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use the appropriate Python version

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            zip \
            unzip \
            build-essential \
            git \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            automake \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libreadline-dev \
            libncursesw5-dev \
            uuid-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good

      - name: Build Android APK
        run: |
          buildozer android clean
          buildozer android debug
